export default {
  obstacles: [
    // Regular Bricks
    //Left Column
    {type: "brick", x: 50, y: 50,  orientation: "horizontal"},
    {type: "brick", x: 50, y: 75,  orientation: "horizontal"},
    {type: "brick", x: 50, y: 100, orientation:  "horizontal"},
    {type: "brick", x: 50, y: 125, orientation:  "horizontal"},
    {type: "brick", x: 50, y: 150, orientation:  "horizontal"},
    {type: "brick", x: 50, y: 175, orientation:  "horizontal"},
    {type: "brick", x: 50, y: 200, orientation:  "horizontal"},
    {type: "brick", x: 50, y: 225, orientation:  "horizontal"},
    {type: "brick", x: 50, y: 400, orientation:  "horizontal"},
    {type: "brick", x: 50, y: 425, orientation:  "horizontal"},
    {type: "brick", x: 50, y: 450, orientation:  "horizontal"},
    {type: "brick", x: 50, y: 475, orientation:  "horizontal"},
    {type: "brick", x: 50, y: 500, orientation:  "horizontal"},
    {type: "brick", x: 50, y: 525, orientation:  "horizontal"},
    {type: "brick", x: 50, y: 550, orientation:  "horizontal"},

    {type: "brick", x: 150, y: 50,  orientation: "horizontal"},
    {type: "brick", x: 150, y: 75,  orientation: "horizontal"},
    {type: "brick", x: 150, y: 100, orientation:  "horizontal"},
    {type: "brick", x: 150, y: 125, orientation:  "horizontal"},
    {type: "brick", x: 150, y: 150, orientation:  "horizontal"},
    {type: "brick", x: 150, y: 175, orientation:  "horizontal"},
    {type: "brick", x: 150, y: 200, orientation:  "horizontal"},
    {type: "brick", x: 150, y: 225, orientation:  "horizontal"},
    {type: "brick", x: 150, y: 400, orientation:  "horizontal"},
    {type: "brick", x: 150, y: 425, orientation:  "horizontal"},
    {type: "brick", x: 150, y: 450, orientation:  "horizontal"},
    {type: "brick", x: 150, y: 475, orientation:  "horizontal"},
    {type: "brick", x: 150, y: 500, orientation:  "horizontal"},
    {type: "brick", x: 150, y: 525, orientation:  "horizontal"},
    {type: "brick", x: 150, y: 550, orientation:  "horizontal"},

    //Central 
    {type: "brick", x: 250, y: 50,  orientation: "horizontal"},
    {type: "brick", x: 250, y: 75,  orientation: "horizontal"},
    {type: "brick", x: 250, y: 100, orientation:  "horizontal"},
    {type: "brick", x: 250, y: 125, orientation:  "horizontal"},
    {type: "brick", x: 250, y: 150, orientation:  "horizontal"},
    {type: "brick", x: 250, y: 175, orientation:  "horizontal"},
    {type: "brick", x: 250, y: 400, orientation:  "horizontal"},
    {type: "brick", x: 250, y: 425, orientation:  "horizontal"},
    {type: "brick", x: 250, y: 450, orientation:  "horizontal"},
    {type: "brick", x: 250, y: 475, orientation:  "horizontal"},

    {type: "brick", x: 350, y: 50,  orientation: "horizontal"},
    {type: "brick", x: 350, y: 75,  orientation: "horizontal"},
    {type: "brick", x: 350, y: 100, orientation:  "horizontal"},
    {type: "brick", x: 350, y: 125, orientation:  "horizontal"},
    {type: "brick", x: 350, y: 150, orientation:  "horizontal"},
    {type: "brick", x: 350, y: 175, orientation:  "horizontal"},
    {type: "brick", x: 350, y: 400, orientation:  "horizontal"},
    {type: "brick", x: 350, y: 425, orientation:  "horizontal"},
    {type: "brick", x: 350, y: 450, orientation:  "horizontal"},
    {type: "brick", x: 350, y: 475, orientation:  "horizontal"},

    // Central Middle
    {type: "brick", x: 100, y: 300, orientation:  "horizontal"},
    {type: "brick", x: 100, y: 325, orientation:  "horizontal"},
    {type: "brick", x: 150, y: 300, orientation:  "horizontal"},
    {type: "brick", x: 150, y: 325, orientation:  "horizontal"},

    {type: "brick", x: 450, y: 300, orientation:  "horizontal"},
    {type: "brick", x: 450, y: 325, orientation:  "horizontal"},
    {type: "brick", x: 500, y: 300, orientation:  "horizontal"},
    {type: "brick", x: 500, y: 325, orientation:  "horizontal"},

    {type: "brick", x: 250, y: 250, orientation:  "horizontal"},
    {type: "brick", x: 250, y: 275, orientation:  "horizontal"},
    {type: "brick", x: 350, y: 250, orientation:  "horizontal"},
    {type: "brick", x: 350, y: 275, orientation:  "horizontal"},

    {type: "brick", x: 250, y: 350, orientation:  "horizontal"},
    {type: "brick", x: 250, y: 375, orientation:  "horizontal"},
    {type: "brick", x: 350, y: 350, orientation:  "horizontal"},
    {type: "brick", x: 350, y: 375, orientation:  "horizontal"},

    {type: "brick", x: 300, y: 375, orientation:  "horizontal"},
    {type: "brick", x: 300, y: 400, orientation:  "horizontal"},
    
    // Rigth
    {type: "brick", x: 450, y: 50,  orientation: "horizontal"},
    {type: "brick", x: 450, y: 75,  orientation: "horizontal"},
    {type: "brick", x: 450, y: 100, orientation:  "horizontal"},
    {type: "brick", x: 450, y: 125, orientation:  "horizontal"},
    {type: "brick", x: 450, y: 150, orientation:  "horizontal"},
    {type: "brick", x: 450, y: 175, orientation:  "horizontal"},
    {type: "brick", x: 450, y: 200, orientation:  "horizontal"},
    {type: "brick", x: 450, y: 225, orientation:  "horizontal"},
    {type: "brick", x: 450, y: 400, orientation:  "horizontal"},
    {type: "brick", x: 450, y: 425, orientation:  "horizontal"},
    {type: "brick", x: 450, y: 450, orientation:  "horizontal"},
    {type: "brick", x: 450, y: 475, orientation:  "horizontal"},
    {type: "brick", x: 450, y: 500, orientation:  "horizontal"},
    {type: "brick", x: 450, y: 525, orientation:  "horizontal"},
    {type: "brick", x: 450, y: 550, orientation:  "horizontal"},

    {type: "brick", x: 550, y: 50,  orientation: "horizontal"},
    {type: "brick", x: 550, y: 75,  orientation: "horizontal"},
    {type: "brick", x: 550, y: 100, orientation:  "horizontal"},
    {type: "brick", x: 550, y: 125, orientation:  "horizontal"},
    {type: "brick", x: 550, y: 150, orientation:  "horizontal"},
    {type: "brick", x: 550, y: 175, orientation:  "horizontal"},
    {type: "brick", x: 550, y: 200, orientation:  "horizontal"},
    {type: "brick", x: 550, y: 225, orientation:  "horizontal"},
    {type: "brick", x: 550, y: 400, orientation:  "horizontal"},
    {type: "brick", x: 550, y: 425, orientation:  "horizontal"},
    {type: "brick", x: 550, y: 450, orientation:  "horizontal"},
    {type: "brick", x: 550, y: 475, orientation:  "horizontal"},
    {type: "brick", x: 550, y: 500, orientation:  "horizontal"},
    {type: "brick", x: 550, y: 525, orientation:  "horizontal"},
    {type: "brick", x: 550, y: 550, orientation:  "horizontal"},

    // Metal Bricks
    {type: "metal", x: 0,   y: 325, orientation: 'horizontal'},
    {type: "metal", x: 600, y: 325, orientation: 'horizontal'},
    {type: "metal", x: 300, y: 125, orientation: 'horizontal'},
    {type: "metal", x: 300, y: 150, orientation: 'horizontal'},

    // Eagle
    {type: "brick", x: 275, y: 575, orientation:  "horizontal"},
    {type: "brick", x: 325, y: 575, orientation:  "horizontal"},

    {type: "brick", x: 275, y: 600, orientation:  "vertical"},
    {type: "brick", x: 350, y: 600, orientation:  "vertical"},

    {type: "eagle", x: 300, y: 600, orientation: 'horizontal'}
  ],
  tanks: [
    {x: 0, y: 0, kind: 'regular'},
    {x: 300, y: 0, kind: 'regular'},
    {x: 600, y: 0, kind: 'regular'},
    {x: 0, y: 0, kind: 'regular'},
    {x: 300, y: 0, kind: 'regular'},
    {x: 600, y: 0, kind: 'regular'},
    {x: 0, y: 0, kind: 'regular'},
    {x: 300, y: 0, kind: 'regular'},
    {x: 600, y: 0, kind: 'regular'},
    {x: 0, y: 0, kind: 'regular'},
    {x: 300, y: 0, kind: 'regular'},
    {x: 600, y: 0, kind: 'regular'},

    {x: 0, y: 0, kind: 'quick'},
    {x: 30, y: 0, kind: 'quick'},
    {x: 600, y: 0, kind: 'quick'}
  ]
};